name: Build Frontend

on:
  push:
    paths: "Frontend/**"
  workflow_dispatch:
jobs:
  build:
    defaults:
      run:
        working-directory: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20"
      - name: Authenticate NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: npm i
        run: npm i
      - name: Install Packages
        run: npm ci --force
      - name: Build
        run: npm run build
